### ISSUE TITLE
<abstract> needs to be inside <info>

### ISSUE THREAD

**Issue by kkaempf** [openSUSE/asciidoctor#1]
Otherwise daps barf at it with "error: element "abstract" not allowed here"

**Comment by kkaempf** [comment]
asciidoctor implements docbook 4.5 here with `<abstract>` inside `<preamble>` following `<info>`.
However, docbook5 require `<abstract>` to be inside `<info>`.

**Comment by kkaempf** [comment]
Fixed

**Comment by jcayouette** [comment]
Nice works thanks!
